sudo: true
language: node_js
node_js:
- 6.1.x
env:
  secure: oXb0wRy8Js1Pk7dScZ/qLuZdHcR/3UGRzRzaABHLDQVgkfchkOtr7pBfb8f+BxIRVvZRFRgzhHef2st090Xna9zMuGHwdQAJmsmKP2+5tBNMwLCcvEzAu+4ZQHkctiRgSifWLjjKyINdvW1NzTxHLm4XqsZRvFPalKVIqEh8oZmRB6sEomwWh4WPC86q5CJrysagzrbHmPrJ2l4ZKZ55W59gHh4HgXpdh7AEdVD8/F4TpNGBt7e6WtRwhx0BPQyKxaZgRzh46oswCbA+ab+SgUq5dogOav8Uec/MwQFnqEHkdXwpWJ70q+k2yC3ajRUEQVjlstsF+LuWPehwIS9eBdo3LJssgAnOJdq3wOC7rjqij29m917KwM2hSRlDVyG2dK/6pZLS9vfaB9w/UpFQILYVpahpVztTo7ljLkFvxpYoeYmigzYiDHW4Zm3AHrMu7pBkN3dfKNaqkmxYxcMvuHmfjGlpP9k1c6iFs/5CTxRJ8yXCKMrvPg8dW5iXtJKBKaq4KK17bv+xKT8bMMplmwvM9LuYDDfwwW10mqN4je9B5KrYEklmDG8lL7Tdt8r+oJazjQe3BTqBdtN46MpGXCFrAareoKoDcZuaRHgY3Ovn4GeGJCuXm7RyjmIJ7fLH4+UuhPPed4F+Iszg3KmikVLFLfJf4vvg630tT3M1MYM=
install:
- wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version
- npm install -g firebase-tools
script:
- mkdir themes
- git clone https://github.com/mantrayatra/hugo-mantra-yatra.git themes/hugo-mantra-yatra
- hugo -v
after_success:
- firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
