sudo: false
language: node_js
node_js:
  - 6.9.2
env:
  - secure: "hQkNCgl8baP34Q1Y5DvQzjlXI7E7ecRuaXIL5BhFHYHuRU6mDpil0b83Nsl6kfRQq9JvPnUZduzLuVFIAjbEdcJgivO3IabTAsPk0gXY8gg4ta5UyO7hTi9lc3h6JVShL9wB1gEiadsXW0ae7OOyUZ9DoIE3gTaCeP1hTJ+1Xo+fd/mPZeVGVv94PFCcX1FrgJG/wQWNsDWzjuUtVHOBuyk79l3f8ZefL44xhBiUwd7C07xU1Ln2lR3PsWVkpOI9bIASQtdft7fMnJ3lwRHyqnRdUU053fxo8C53NYTd3UX0ajm5g9aaznIDu/ChADHRNBfnfGBC+8Isy+oYpV90AY0Wi6DRM++mhz6naVaotgglD+PfIgL0/RsXVWbh3fLtRqbWE7D2TKIoBg/XMoUZkkdEBzT4Ti9c2305UJi6XKQZ72WeisOltgRzBIwsKm0MgorXlwi4+sj9UfNCcXsqWnxaUzq82PtZmEvyMOlUjymS+RodRhm7UOKoGcZgm14vEqh6eIv5e/L1XANGQ540qQHFaPNWoPAuf2Joh9/FILVt2bVh+23uXEmA3Lqv+q/arwY+jSDBqDnAQEqBHdyDhnpgRw6KBcmOY9Gz7STsy4gFdKyaBvacIyDiz81RJxaQx1P+6Ae357WfDua4Wppl9PKdr58TB7TqGjs2INT9FWE="
  - HUGO_VERSION="0.17"
cache:
  yarn: true
  directories:
    - node_modules
    - tools
install:
  - wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz \
    && tar -xzf hugo_*.tar.gz && mkdir tools && cp hugo*/hugo* tools/hugo && rm -rf hugo_*
  - ./hugo version
  - yarn --version
  - yarn install
script:
  - mkdir themes
  - git clone https://github.com/mantrayatra/hugo-mantra-yatra.git themes/hugo-mantra-yatra
  - ./hugo -v
after_success:
  - node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
