sudo: false
language: node_js
node_js:
  - 10.14.2
env:
  global:
    - secure: "mJ7LTDB8xCRfWFcSLR0PRputVQ0NfEUrxqIB/SvKDE6SfqD83OunvANGRYhpxS8pvPkTHByogrU2Wn01Vloch8lgmU3U2gErd97vcY/EObMVbv74DQR6MxL2+154v7jD/OR5ZSRQ9PEwStm/IIiHZpK9fwkWk5g4NSsOONCOvu+Sq5IpkpDJONdxyw4A0YXA1Ljh4fvj+E+g7JAXVkG2yUxs9ivxBx/Ewyh5xJTxjOa3+3HWw3BBs/msXC2NlxLqTzjjA2WVAmAE/Cj7Jo0DuFbowgY5UGXDtg51inIWqB+HfgbZLXUlIinccDSJay/c1UaZobIMH2LVXltHC52THG2Vz2dVIts7CpWij5BY0zVDgnkqOticKwZngkozce4CTfUh5nv4TpzVmBnSum3+owsS2XsJOw9QJ1GxP2kjuDh4alwM7jOJkEdZo+woHJALNjgEekAQNwAhmxTIR+rQ6s61D6SiSe7AREGX9xRoVA5vjNfGezURFfCMqnXCrYTjSWbLNaDwxG3HuhVglvYxhwjbJMURxaIaBGStfNvICdq7J8yb+rU+ssvbhPz9kCPZKDGKWA5U3Q888bO+pmdWMBAW/gn6aQwuIYKubN/m63FQ8Zz46iMkA3dd8EwIt32Sk7hKNHv6u6lJYovQqrCNo8rOo7BnWVj6nDLWWgPeOOU="
  matrix:
    - HUGO_VERSION="0.52"
cache:
  directories:
    - node_modules
    - tools
install:
  - ./install_dependencies.sh "$HUGO_VERSION"
script:
  - mkdir themes
  - git clone https://github.com/mantrayatra/hugo-mantra-yatra.git themes/hugo-mantra-yatra
  - tools/hugo -v
after_success:
  - node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
