sudo: false
language: go
go:
  - 1.7.x
install:
  - go get -u -v github.com/spf13/hugo
  - hugo version
script:
  - mkdir themes
  - git clone https://github.com/mantrayatra/hugo-mantra-yatra.git themes
  - hugo -v
