baseurl = "https://mantrayatra.com/"
title = "Mantra yatra"
languageCode = "en-us"
theme = "hugo-mantra-yatra"

[params]
  bannerImgUrl = "//res.cloudinary.com/mantrayatra/image/upload/v1481461144/kailash-manasarovar/banner.jpg"
