backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
public_folder: "/images/uploads" 
publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: mantrayatra
    api_key: 822225168392362
collections:
  - name: "yatra"
    label: "Yatras"
    folder: "content/yatra"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Title Image", name: "image", widget: "image"}
      - {label: "Title Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "testimonials"
    label: "Testimonials"
    folder: "data/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Work Position", name: "position", widget: "string"}
      - {label: "Testimonial", name: "text", widget: "string"}
      - {label: "Profile pic", name: "avatar", widget: "image"}
