backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
media_folder: "static/images/uploads"
public_folder: "/images/uploads" 
publish_mode: editorial_workflow
collections:
  - name: "yatra"
    label: "Yatra"
    folder: "content/yatra"
    create: true 
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Title Image", name: "image", widget: "image"}
      - {label: "Title Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}